name: Comunicador de la Legión

on:
  workflow_dispatch:
    inputs:
      villano:
        description: "¿Que villano envía el mensaje?"
        required: true
        type: choice
        options:
          - Lex Luthor
          - Magneto
          - Joker
          - Mystique
      
      prioridad:
        description: "¿Que nivel de prioridad quieres?"
        required: true
        type: choice
        options:
          - 🟢 Normal
          - 🟡 Alta
          - 🔴 Critica

      mensaje:
        description: "¿Que mensaje quieres para el consejo?"
        required: true
        default: "La misión fue un éxito"


jobs:
  transmitir-mensaje:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar el transmisor de la Legión
        run: sudo apt-get install -y cowsay

      - name: Imprimir inputs
        run: |
          echo "================================"
          echo "    Transmisión interceptada    "
          echo "================================"
          echo ""
          echo "De: ${{inputs.villano}}"
          echo ""
          echo "Fecha: $(date -u +"%d/%m/%Y - %H:%M UTC")"
          echo "------- Mensaje --------"
          cowsay -f eyes "${{inputs.mensaje}}"
          echo ""
          echo "----- ${{inputs.villano}}"
          echo "..."
